### PR TITLE
New user added

### PR DESCRIPTION
**Pull request by Aryainguz**
*Updated gitfetch.js and added myself as new user

### CODE REVIEW

**Comment by Boltjazz** [comment]
hi Aryan thankyou for your contribution just , you code has a different branch , co i am not able to see the changer or merge it , please change the new-user banch to main then create apull req

**Comment by Aryainguz** [comment]
> hi Aryan thankyou for your contribution just , you code has a different branch , co i am not able to see the changer or merge it , please change the new-user banch to main then create apull req

Updated it

**Comment by Aryainguz** [comment]
I’ve opened a new pull request from main fixing the previous issue really
sorry for that

**Comment by Aryainguz** [comment]
Really sorry for few errors, I’ve successfully completed all issues now

**Comment by Aryainguz** [comment]
Please merge my pull requests I’ve successfully solve all issue and
conflicts

**Pull request closed without merging**
