### PR TITLE
Task2 Does_it_divide.Cpp

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Here is the solution for the Task2 Does_it_divide in C++ ;

Please consider this under hacktoberfest : )

### CODE REVIEW

**Comment by Boltjazz** [comment]
@Bharath-KumarReddy 
In Does it divide problem can you add comments in the code and an output link separating YEA and NAH

**Comment by Bharath-KumarReddy** [comment]
Yes sure : )

**Comment by Bharath-KumarReddy** [comment]
Whether I need to add or change any codes further ??

**Comment by Bharath-KumarReddy** [comment]
Hi.
Can you change the repo rules so that it will obey the rules of hacktoberfest_23 , My PR is excluded due to this repo is not obeying the laws or rules of hacktoberfest_23

**Pull request merged**
